import type { Metadata } from 'next';
import ReactQueryProvider from './reactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <div
            style={{
              fontSize: '1.3rem',
              marginBottom: '1rem',
              marginTop: '1rem',
            }}
          >
            todos:
          </div>
          {children}
          <ReactQueryDevtools
            initialIsOpen={false}
            position='left'
            buttonPosition='bottom-left'
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
